# mybatis
mybatis:
  type-aliases-package: com.zgb.spring.boot.quartz.demo.pojo.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  kafka:
#    bootstrap-servers: 10.200.20.194:9092
#    consumer:
#      group-id: quartzdemo
#      auto-offset-reset: earliest
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    enabled: true
#    encoding: UTF-8
#    mode: HTML