spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

### h2 内存数据库
###数据库连接设置
##配置h2数据库的连接地址
#spring:
#  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
#
#    ##数据初始化设置
#    #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
#    schema: classpath:db/schema.sql
#    #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
#    data: classpath:db/data.sql


# 测试自动配置
demo:
  name: test auto configure